// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQr9KmrGIvWSWrtXt2QK0Cf9_TGBw770',
    appId: '1:182624705218:web:122f319f65223e7fa3f95b',
    messagingSenderId: '182624705218',
    projectId: 'synclist-3fefb',
    authDomain: 'synclist-3fefb.firebaseapp.com',
    storageBucket: 'synclist-3fefb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5B5FXUCxp9CGJ7A8QrfxLJJjIBMItkJk',
    appId: '1:182624705218:android:dcadb14911eb30dca3f95b',
    messagingSenderId: '182624705218',
    projectId: 'synclist-3fefb',
    storageBucket: 'synclist-3fefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmJkXDSrkFQXv6OB-5Slmjr6tH8KdpuY',
    appId: '1:182624705218:ios:2d72f253880b4f2ba3f95b',
    messagingSenderId: '182624705218',
    projectId: 'synclist-3fefb',
    storageBucket: 'synclist-3fefb.firebasestorage.app',
    iosBundleId: 'com.example.syncList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmJkXDSrkFQXv6OB-5Slmjr6tH8KdpuY',
    appId: '1:182624705218:ios:2d72f253880b4f2ba3f95b',
    messagingSenderId: '182624705218',
    projectId: 'synclist-3fefb',
    storageBucket: 'synclist-3fefb.firebasestorage.app',
    iosBundleId: 'com.example.syncList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQr9KmrGIvWSWrtXt2QK0Cf9_TGBw770',
    appId: '1:182624705218:web:2612d91c30b34947a3f95b',
    messagingSenderId: '182624705218',
    projectId: 'synclist-3fefb',
    authDomain: 'synclist-3fefb.firebaseapp.com',
    storageBucket: 'synclist-3fefb.firebasestorage.app',
  );
}
